script: bundle exec rspec spec
cache: bundler
language: ruby
rvm:
- 2.4.1
- 2.3.4
- jruby-9.1.2.0
notifications:
  flowdock:
    secure: XHbGGBBN9XBMcAEr+NR1kzQUsLhXdolZ5hW0LIkf0oM1dkpPBrm7m3hKMZXq2OdwouUa0mgrt2Yz1T21mXX7bI//or92lVgWd/a1ptQcL/SN2j7/fN0PvD0KZWbY74poZU8I+hatKPXpVWGB5jsFlpROFAmTTvLz9T2XHNnQm91B7IQjbKRc/6p+2ZoW0avlsUgcUbtih5aitJj30xuwzVXVcaWb/bzuloMz5B3L3kw6tsgTzyJCr1x/BJBsxJQI8jVEzOtc09XNEbeQD9ZQl+7DRN51Q1iq1PiubpIgfNgpyTgqQvPp614T7yiPmvvypBkb6apN4BSJupaeWc8UTjroZvtUNCUQaefzYB/P3zXOS/ZGmXbD3Me3V5KTNpmZ5fx8MbUzTeU5iH4pVHvuf9oiVGah4vlDA2aUjk6PIxdAUVf7jE4/wbNYSi4TlH/DqBGBc1HB6M3/toVJ+BVqnZSfbOwpQOJv2ZY7OLI81uVmMgUyUeUKVxIjSb5YDhH7jh/cNS/FdHGCgMKKTLvJmNoIHKL8Y0dgH3bZWh7yzKpCpkkyXrqZSuAEtSD7Oc5u5QRZWtC9vfi61UFXBgyfbTh/nwgJ+OXZ2JyFjBgCPbs4EvH+0OZaPLFhpDNKTOs/aDHekdXnO0+SNPGxKb2w4Tb5GxKnK+Q2ZXOHETATMt8=
